apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:dr14-make/kube-workshop-learning-days-2024.git
        revision: HEAD
        files:
          - path: "applications/*.yaml"
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: { { .project | default default } }
      source:
        repoURL: git@github.com:dr14-make/kube-workshop-learning-days-2024.git
        targetRevision: "{{ .targetRevision | default HEAD}}"
        path: "{{ .path }}"
      destination:
        server: "{{ .cluster | default https://kubernetes.default.svc }}"
        namespace: "{{ .namespace }}"
  templatePatch: |
    spec:
      source:
        helm:
          releaseName: {{ .releaseName }}
          valueFiles:
          {{- range $valueFile := .valueFiles }}
            - {{ $valueFile }}
          {{- end }}
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .prune }}
    {{- end }}
