apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.storeName }}
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.auth.name | default "dopler-token" }}
            key: {{ .Values.auth.key | default "apitoken.txt" }}
            namespace: {{ .Values.auth.namespace | default "default" }}
